Class {
	#name : #PLSCellMimetype,
	#superclass : #Object,
	#category : 'PharoLanguageServer-Structure-Moosebook'
}

{ #category : #'as yet unclassified' }
PLSCellMimetype class >> errorType [

	^ 'error'
]

{ #category : #'as yet unclassified' }
PLSCellMimetype class >> html [

	^ 'text/html'
]

{ #category : #'as yet unclassified' }
PLSCellMimetype class >> markdown [

	^ 'text/markdown'
]

{ #category : #'as yet unclassified' }
PLSCellMimetype class >> png [

	^ 'image/png'
]
