"
The kind of a completion entry.
"
Class {
	#name : #PLSCompletionItemKind,
	#superclass : #Object,
	#category : 'PharoLanguageServer-Structure-Completion'
}

{ #category : #accessing }
PLSCompletionItemKind class >> class1 [
	^ 7
]

{ #category : #accessing }
PLSCompletionItemKind class >> color [
	^ 16
]

{ #category : #accessing }
PLSCompletionItemKind class >> constructor [
	^ 4
]

{ #category : #accessing }
PLSCompletionItemKind class >> contant [
	^ 21
]

{ #category : #accessing }
PLSCompletionItemKind class >> enum [
	^ 13
]

{ #category : #accessing }
PLSCompletionItemKind class >> enumMember [
	^ 20
]

{ #category : #accessing }
PLSCompletionItemKind class >> event [
	^ 23
]

{ #category : #accessing }
PLSCompletionItemKind class >> field [
	^ 5
]

{ #category : #accessing }
PLSCompletionItemKind class >> file [
	^ 17
]

{ #category : #accessing }
PLSCompletionItemKind class >> folder [
	^ 19
]

{ #category : #accessing }
PLSCompletionItemKind class >> function [
	^ 3 
]

{ #category : #accessing }
PLSCompletionItemKind class >> interface [
	^ 8
]

{ #category : #accessing }
PLSCompletionItemKind class >> keyword [
	^ 14
]

{ #category : #accessing }
PLSCompletionItemKind class >> method [
	^ 2
]

{ #category : #accessing }
PLSCompletionItemKind class >> module [
	^ 9
]

{ #category : #accessing }
PLSCompletionItemKind class >> operator [
	^ 24
]

{ #category : #accessing }
PLSCompletionItemKind class >> property [
	^ 10
]

{ #category : #accessing }
PLSCompletionItemKind class >> reference [ 
	^ 18
	
]

{ #category : #accessing }
PLSCompletionItemKind class >> snippet [ 
	^ 15
]

{ #category : #accessing }
PLSCompletionItemKind class >> struct [
	^ 22 
]

{ #category : #accessing }
PLSCompletionItemKind class >> text [
	^ 1
]

{ #category : #accessing }
PLSCompletionItemKind class >> typeParameter [
	^ 25
]

{ #category : #accessing }
PLSCompletionItemKind class >> unit [
	^ 11
]

{ #category : #accessing }
PLSCompletionItemKind class >> value1 [
	^ 12
]

{ #category : #accessing }
PLSCompletionItemKind class >> variable [
	^ 6
]
