"
A symbol kind.
"
Class {
	#name : #PLSSymbolKind,
	#superclass : #Object,
	#category : #'PharoLanguageServer-Structure-Symbols'
}

{ #category : #accessing }
PLSSymbolKind class >> array [
	^ 18
]

{ #category : #accessing }
PLSSymbolKind class >> boolean [
	^ 17
]

{ #category : #accessing }
PLSSymbolKind class >> classID [
	^ 4
]

{ #category : #accessing }
PLSSymbolKind class >> constant [
	^ 14
]

{ #category : #accessing }
PLSSymbolKind class >> constructor [
	^ 9
]

{ #category : #accessing }
PLSSymbolKind class >> enum [
	^ 10
]

{ #category : #accessing }
PLSSymbolKind class >> enumMember [
	^ 22
]

{ #category : #accessing }
PLSSymbolKind class >> event [
	^ 24
]

{ #category : #accessing }
PLSSymbolKind class >> field [
	^ 8
]

{ #category : #accessing }
PLSSymbolKind class >> file [
	^ 1
]

{ #category : #accessing }
PLSSymbolKind class >> function [
	^ 12
]

{ #category : #accessing }
PLSSymbolKind class >> interface [
	^ 11
]

{ #category : #accessing }
PLSSymbolKind class >> key [
	^ 20
]

{ #category : #accessing }
PLSSymbolKind class >> method [
	^ 6
]

{ #category : #accessing }
PLSSymbolKind class >> module [
	^ 2
]

{ #category : #accessing }
PLSSymbolKind class >> namespace [
	^ 3
]

{ #category : #accessing }
PLSSymbolKind class >> null [
	^ 21
]

{ #category : #accessing }
PLSSymbolKind class >> number [
	^ 16
]

{ #category : #accessing }
PLSSymbolKind class >> object [
	^ 19
]

{ #category : #accessing }
PLSSymbolKind class >> operator [
	^ 25
]

{ #category : #accessing }
PLSSymbolKind class >> packageID [
	^ 4
]

{ #category : #accessing }
PLSSymbolKind class >> property [
	^ 7
]

{ #category : #accessing }
PLSSymbolKind class >> string [
	^ 15
]

{ #category : #accessing }
PLSSymbolKind class >> struct [
	^ 23
]

{ #category : #accessing }
PLSSymbolKind class >> typeParameter [
	^ 26
]

{ #category : #accessing }
PLSSymbolKind class >> variable [
	^ 13
]
