"
[https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#traceValue](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#traceValue)
"
Class {
	#name : 'PLSTraceValue',
	#superclass : 'Object',
	#category : 'PharoLanguageServer-Structure-Trace',
	#package : 'PharoLanguageServer',
	#tag : 'Structure-Trace'
}

{ #category : 'as yet unclassified' }
PLSTraceValue class >> messages [

	^ 'messages'
]

{ #category : 'as yet unclassified' }
PLSTraceValue class >> off [

	^ 'off'
]

{ #category : 'as yet unclassified' }
PLSTraceValue class >> verbose [

	^ 'verbose'
]
