# This is a basic workflow to help you get started with Actions

name: Continuous

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches: 
      - main
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ matrix.smalltalk }}-PLS
    strategy:
      matrix:
        smalltalk: [ Pharo64-11, Moose64-11 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: ${{ matrix.smalltalk == 'Moose64-11' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}